version: '3'

services:
  my-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mytestdb
    ports:
      - "5434:5432"

  asynctasks_redis:
    image: redis:4.0.6-alpine
    ports:
      - "6380:6379"
    depends_on:
      - my-postgres

  async-tasks:
    image: r1murzin/async-tasks:latest
    environment:
      - DATABASE_URL=postgres+psycopg2://postgres:mysecretpassword@172.18.0.2:5432/mytestdb
      - REDIS_URL=redis://asynctasks_redis:6379
    ports:
      - "5000:5000"
    depends_on:
      - asynctasks_redis
      - my-postgres
    command: bash -c "sleep 10 && flask db upgrade && python main.py"

  async-tasks_worker1:
    image: r1murzin/async-tasks:latest
    command: rq worker --url redis://asynctasks_redis:6379 asynctasks-tasks
    depends_on:
    depends_on:
      - asynctasks_redis
      - my-postgres
  async-tasks_worker2:
    image: r1murzin/async-tasks:latest
    command: rq worker --url redis://asynctasks_redis:6379 asynctasks-tasks
    depends_on:
    depends_on:
      - asynctasks_redis
      - my-postgres
  async-tasks_worker3:
    image: r1murzin/async-tasks:latest
    command: rq worker --url redis://asynctasks_redis:6379 asynctasks-tasks
    depends_on:
    depends_on:
      - asynctasks_redis
      - my-postgres