version: '3'

services:
  async-tasks_test:
    image: r1murzin/async-tasks:latest
    environment:
      - HOST_URL=http://async-tasks:5000
    command: bash -c "pip install pytest && ./wait-for-it.sh async-tasks:5000 -- pytest tests.py"